#!/usr/bin/env python
# -*- encoding: utf-8 -*-
#
# Swift object dispersion report monitoring script for Nagios
#
# Authors:
#   Rakesh Patnaik <patsrakesh@gmail.com>
#
# This file is part of nagios-openstack-monitoring
# (https://github.com/rakesh-patnaik/nagios-openstack-monitoring)
#
# nagios-openstack-monitoring is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# nagios-openstack-monitoring is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with nagios-openstack-monitoring.  If not, see <http://www.gnu.org/licenses/>.>.
#
# Requirments: python-keystoneclient, python-argparse, python

import os
import sys
import json

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

with os.popen("swift-dispersion-report -j %s" \
                  % os.getenv("SWIFT_DISPERSION_CONFIG", "/etc/swift/dispersion.conf")) as report:
    stats = json.load(report)

msgs = []
state = STATE_OK

# type_ is either "objects", "container"
for type_, values in stats.iteritems():

    msgs.append("%.2f%% %ss found" % (values['pct_found'], type_))

    if values['missing_one'] > 0:
        msgs.append("%d %ss missing one copy" % (values['missing_one'], type_))
        state = max(state, STATE_WARNING)

    if values['missing_two'] > 0:
        msgs.append("%d %ss missing two copies" % (values['missing_two'], type_))
        state = max(state, STATE_WARNING)

    if values['missing_all'] > 0:
        msgs.append("%d %ss missing ALL copies" % (values['missing_all'], type_))
        state = max(state, STATE_CRITICAL)

print ", ".join(msgs)
sys.exit(state)
